---
dependency:
   name: galaxy
driver:
   name: ec2
platforms:
  - name: instance
    image_owner: 099720109477
    image_name: ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*
    instance_type: t2.micro
    vpc_subnet_id: {{ cookiecutter.subnet_id }}
    tags:
      - Name: molecule_instance
provisioner:
  name: ansible
verifier:
  name: ansible